index:
    path: /
    controller: App\Controller\DefaultController::index

register:
    path: /register
    controller: App\Controller\RegisterController::index

todos:
    path: /todos
    controller: App\Controller\TodosController::index
