index:
    path: /
    controller: App\Controller\DefaultController::index

register:
    path: /register
    controller: App\Controller\RegisterController::registerAction

todos:
    path: /todos
    controller: App\Controller\TodosController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
